#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

#cleanCase0 deletes all the time step directories, including 0, another option is cleanCase
cleanCase0

rm ./dragCoeffPlot.png
#------------------------------------------------------------------------------
