#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

cp -r 0.org 0

runApplication blockMesh

runApplication topoSet

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

gnuplot dragCoeffPlot.gplt

foamListTimes -rm -time 0.05:15.95

rm -r processor*

#------------------------------------------------------------------------------
